package com.tech.pojo;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class DealExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public DealExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDealIdIsNull() {
            addCriterion("deal_id is null");
            return (Criteria) this;
        }

        public Criteria andDealIdIsNotNull() {
            addCriterion("deal_id is not null");
            return (Criteria) this;
        }

        public Criteria andDealIdEqualTo(Integer value) {
            addCriterion("deal_id =", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotEqualTo(Integer value) {
            addCriterion("deal_id <>", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThan(Integer value) {
            addCriterion("deal_id >", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("deal_id >=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThan(Integer value) {
            addCriterion("deal_id <", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdLessThanOrEqualTo(Integer value) {
            addCriterion("deal_id <=", value, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdIn(List<Integer> values) {
            addCriterion("deal_id in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotIn(List<Integer> values) {
            addCriterion("deal_id not in", values, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdBetween(Integer value1, Integer value2) {
            addCriterion("deal_id between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andDealIdNotBetween(Integer value1, Integer value2) {
            addCriterion("deal_id not between", value1, value2, "dealId");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andDealCostIsNull() {
            addCriterion("deal_cost is null");
            return (Criteria) this;
        }

        public Criteria andDealCostIsNotNull() {
            addCriterion("deal_cost is not null");
            return (Criteria) this;
        }

        public Criteria andDealCostEqualTo(Float value) {
            addCriterion("deal_cost =", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostNotEqualTo(Float value) {
            addCriterion("deal_cost <>", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostGreaterThan(Float value) {
            addCriterion("deal_cost >", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostGreaterThanOrEqualTo(Float value) {
            addCriterion("deal_cost >=", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostLessThan(Float value) {
            addCriterion("deal_cost <", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostLessThanOrEqualTo(Float value) {
            addCriterion("deal_cost <=", value, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostIn(List<Float> values) {
            addCriterion("deal_cost in", values, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostNotIn(List<Float> values) {
            addCriterion("deal_cost not in", values, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostBetween(Float value1, Float value2) {
            addCriterion("deal_cost between", value1, value2, "dealCost");
            return (Criteria) this;
        }

        public Criteria andDealCostNotBetween(Float value1, Float value2) {
            addCriterion("deal_cost not between", value1, value2, "dealCost");
            return (Criteria) this;
        }

        public Criteria andStartPriceIsNull() {
            addCriterion("start_price is null");
            return (Criteria) this;
        }

        public Criteria andStartPriceIsNotNull() {
            addCriterion("start_price is not null");
            return (Criteria) this;
        }

        public Criteria andStartPriceEqualTo(Float value) {
            addCriterion("start_price =", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceNotEqualTo(Float value) {
            addCriterion("start_price <>", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceGreaterThan(Float value) {
            addCriterion("start_price >", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceGreaterThanOrEqualTo(Float value) {
            addCriterion("start_price >=", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceLessThan(Float value) {
            addCriterion("start_price <", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceLessThanOrEqualTo(Float value) {
            addCriterion("start_price <=", value, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceIn(List<Float> values) {
            addCriterion("start_price in", values, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceNotIn(List<Float> values) {
            addCriterion("start_price not in", values, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceBetween(Float value1, Float value2) {
            addCriterion("start_price between", value1, value2, "startPrice");
            return (Criteria) this;
        }

        public Criteria andStartPriceNotBetween(Float value1, Float value2) {
            addCriterion("start_price not between", value1, value2, "startPrice");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdIsNull() {
            addCriterion("available_coupon_id is null");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdIsNotNull() {
            addCriterion("available_coupon_id is not null");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdEqualTo(Integer value) {
            addCriterion("available_coupon_id =", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdNotEqualTo(Integer value) {
            addCriterion("available_coupon_id <>", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdGreaterThan(Integer value) {
            addCriterion("available_coupon_id >", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("available_coupon_id >=", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdLessThan(Integer value) {
            addCriterion("available_coupon_id <", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdLessThanOrEqualTo(Integer value) {
            addCriterion("available_coupon_id <=", value, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdIn(List<Integer> values) {
            addCriterion("available_coupon_id in", values, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdNotIn(List<Integer> values) {
            addCriterion("available_coupon_id not in", values, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdBetween(Integer value1, Integer value2) {
            addCriterion("available_coupon_id between", value1, value2, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andAvailableCouponIdNotBetween(Integer value1, Integer value2) {
            addCriterion("available_coupon_id not between", value1, value2, "availableCouponId");
            return (Criteria) this;
        }

        public Criteria andDealDesIsNull() {
            addCriterion("deal_des is null");
            return (Criteria) this;
        }

        public Criteria andDealDesIsNotNull() {
            addCriterion("deal_des is not null");
            return (Criteria) this;
        }

        public Criteria andDealDesEqualTo(String value) {
            addCriterion("deal_des =", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesNotEqualTo(String value) {
            addCriterion("deal_des <>", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesGreaterThan(String value) {
            addCriterion("deal_des >", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesGreaterThanOrEqualTo(String value) {
            addCriterion("deal_des >=", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesLessThan(String value) {
            addCriterion("deal_des <", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesLessThanOrEqualTo(String value) {
            addCriterion("deal_des <=", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesLike(String value) {
            addCriterion("deal_des like", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesNotLike(String value) {
            addCriterion("deal_des not like", value, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesIn(List<String> values) {
            addCriterion("deal_des in", values, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesNotIn(List<String> values) {
            addCriterion("deal_des not in", values, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesBetween(String value1, String value2) {
            addCriterion("deal_des between", value1, value2, "dealDes");
            return (Criteria) this;
        }

        public Criteria andDealDesNotBetween(String value1, String value2) {
            addCriterion("deal_des not between", value1, value2, "dealDes");
            return (Criteria) this;
        }

        public Criteria andSaleNumIsNull() {
            addCriterion("sale_num is null");
            return (Criteria) this;
        }

        public Criteria andSaleNumIsNotNull() {
            addCriterion("sale_num is not null");
            return (Criteria) this;
        }

        public Criteria andSaleNumEqualTo(Integer value) {
            addCriterion("sale_num =", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumNotEqualTo(Integer value) {
            addCriterion("sale_num <>", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumGreaterThan(Integer value) {
            addCriterion("sale_num >", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("sale_num >=", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumLessThan(Integer value) {
            addCriterion("sale_num <", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumLessThanOrEqualTo(Integer value) {
            addCriterion("sale_num <=", value, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumIn(List<Integer> values) {
            addCriterion("sale_num in", values, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumNotIn(List<Integer> values) {
            addCriterion("sale_num not in", values, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumBetween(Integer value1, Integer value2) {
            addCriterion("sale_num between", value1, value2, "saleNum");
            return (Criteria) this;
        }

        public Criteria andSaleNumNotBetween(Integer value1, Integer value2) {
            addCriterion("sale_num not between", value1, value2, "saleNum");
            return (Criteria) this;
        }

        public Criteria andDealMainImageIsNull() {
            addCriterion("deal_main_image is null");
            return (Criteria) this;
        }

        public Criteria andDealMainImageIsNotNull() {
            addCriterion("deal_main_image is not null");
            return (Criteria) this;
        }

        public Criteria andDealMainImageEqualTo(String value) {
            addCriterion("deal_main_image =", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageNotEqualTo(String value) {
            addCriterion("deal_main_image <>", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageGreaterThan(String value) {
            addCriterion("deal_main_image >", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageGreaterThanOrEqualTo(String value) {
            addCriterion("deal_main_image >=", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageLessThan(String value) {
            addCriterion("deal_main_image <", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageLessThanOrEqualTo(String value) {
            addCriterion("deal_main_image <=", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageLike(String value) {
            addCriterion("deal_main_image like", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageNotLike(String value) {
            addCriterion("deal_main_image not like", value, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageIn(List<String> values) {
            addCriterion("deal_main_image in", values, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageNotIn(List<String> values) {
            addCriterion("deal_main_image not in", values, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageBetween(String value1, String value2) {
            addCriterion("deal_main_image between", value1, value2, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andDealMainImageNotBetween(String value1, String value2) {
            addCriterion("deal_main_image not between", value1, value2, "dealMainImage");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNull() {
            addCriterion("end_time is null");
            return (Criteria) this;
        }

        public Criteria andEndTimeIsNotNull() {
            addCriterion("end_time is not null");
            return (Criteria) this;
        }

        public Criteria andEndTimeEqualTo(Date value) {
            addCriterion("end_time =", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotEqualTo(Date value) {
            addCriterion("end_time <>", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThan(Date value) {
            addCriterion("end_time >", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("end_time >=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThan(Date value) {
            addCriterion("end_time <", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("end_time <=", value, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeIn(List<Date> values) {
            addCriterion("end_time in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotIn(List<Date> values) {
            addCriterion("end_time not in", values, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeBetween(Date value1, Date value2) {
            addCriterion("end_time between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("end_time not between", value1, value2, "endTime");
            return (Criteria) this;
        }

        public Criteria andUseNumIsNull() {
            addCriterion("use_num is null");
            return (Criteria) this;
        }

        public Criteria andUseNumIsNotNull() {
            addCriterion("use_num is not null");
            return (Criteria) this;
        }

        public Criteria andUseNumEqualTo(Integer value) {
            addCriterion("use_num =", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumNotEqualTo(Integer value) {
            addCriterion("use_num <>", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumGreaterThan(Integer value) {
            addCriterion("use_num >", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("use_num >=", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumLessThan(Integer value) {
            addCriterion("use_num <", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumLessThanOrEqualTo(Integer value) {
            addCriterion("use_num <=", value, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumIn(List<Integer> values) {
            addCriterion("use_num in", values, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumNotIn(List<Integer> values) {
            addCriterion("use_num not in", values, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumBetween(Integer value1, Integer value2) {
            addCriterion("use_num between", value1, value2, "useNum");
            return (Criteria) this;
        }

        public Criteria andUseNumNotBetween(Integer value1, Integer value2) {
            addCriterion("use_num not between", value1, value2, "useNum");
            return (Criteria) this;
        }

        public Criteria andExceptDateIsNull() {
            addCriterion("except_date is null");
            return (Criteria) this;
        }

        public Criteria andExceptDateIsNotNull() {
            addCriterion("except_date is not null");
            return (Criteria) this;
        }

        public Criteria andExceptDateEqualTo(Date value) {
            addCriterion("except_date =", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateNotEqualTo(Date value) {
            addCriterion("except_date <>", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateGreaterThan(Date value) {
            addCriterion("except_date >", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateGreaterThanOrEqualTo(Date value) {
            addCriterion("except_date >=", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateLessThan(Date value) {
            addCriterion("except_date <", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateLessThanOrEqualTo(Date value) {
            addCriterion("except_date <=", value, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateIn(List<Date> values) {
            addCriterion("except_date in", values, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateNotIn(List<Date> values) {
            addCriterion("except_date not in", values, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateBetween(Date value1, Date value2) {
            addCriterion("except_date between", value1, value2, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andExceptDateNotBetween(Date value1, Date value2) {
            addCriterion("except_date not between", value1, value2, "exceptDate");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindIsNull() {
            addCriterion("subscribe_remind is null");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindIsNotNull() {
            addCriterion("subscribe_remind is not null");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindEqualTo(String value) {
            addCriterion("subscribe_remind =", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindNotEqualTo(String value) {
            addCriterion("subscribe_remind <>", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindGreaterThan(String value) {
            addCriterion("subscribe_remind >", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindGreaterThanOrEqualTo(String value) {
            addCriterion("subscribe_remind >=", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindLessThan(String value) {
            addCriterion("subscribe_remind <", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindLessThanOrEqualTo(String value) {
            addCriterion("subscribe_remind <=", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindLike(String value) {
            addCriterion("subscribe_remind like", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindNotLike(String value) {
            addCriterion("subscribe_remind not like", value, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindIn(List<String> values) {
            addCriterion("subscribe_remind in", values, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindNotIn(List<String> values) {
            addCriterion("subscribe_remind not in", values, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindBetween(String value1, String value2) {
            addCriterion("subscribe_remind between", value1, value2, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andSubscribeRemindNotBetween(String value1, String value2) {
            addCriterion("subscribe_remind not between", value1, value2, "subscribeRemind");
            return (Criteria) this;
        }

        public Criteria andCozyTipsIsNull() {
            addCriterion("cozy_tips is null");
            return (Criteria) this;
        }

        public Criteria andCozyTipsIsNotNull() {
            addCriterion("cozy_tips is not null");
            return (Criteria) this;
        }

        public Criteria andCozyTipsEqualTo(String value) {
            addCriterion("cozy_tips =", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsNotEqualTo(String value) {
            addCriterion("cozy_tips <>", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsGreaterThan(String value) {
            addCriterion("cozy_tips >", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsGreaterThanOrEqualTo(String value) {
            addCriterion("cozy_tips >=", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsLessThan(String value) {
            addCriterion("cozy_tips <", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsLessThanOrEqualTo(String value) {
            addCriterion("cozy_tips <=", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsLike(String value) {
            addCriterion("cozy_tips like", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsNotLike(String value) {
            addCriterion("cozy_tips not like", value, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsIn(List<String> values) {
            addCriterion("cozy_tips in", values, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsNotIn(List<String> values) {
            addCriterion("cozy_tips not in", values, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsBetween(String value1, String value2) {
            addCriterion("cozy_tips between", value1, value2, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andCozyTipsNotBetween(String value1, String value2) {
            addCriterion("cozy_tips not between", value1, value2, "cozyTips");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIsNull() {
            addCriterion("totality_review_score is null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIsNotNull() {
            addCriterion("totality_review_score is not null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreEqualTo(Integer value) {
            addCriterion("totality_review_score =", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotEqualTo(Integer value) {
            addCriterion("totality_review_score <>", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreGreaterThan(Integer value) {
            addCriterion("totality_review_score >", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("totality_review_score >=", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreLessThan(Integer value) {
            addCriterion("totality_review_score <", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreLessThanOrEqualTo(Integer value) {
            addCriterion("totality_review_score <=", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIn(List<Integer> values) {
            addCriterion("totality_review_score in", values, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotIn(List<Integer> values) {
            addCriterion("totality_review_score not in", values, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_score between", value1, value2, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_score not between", value1, value2, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumIsNull() {
            addCriterion("totality_review_num is null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumIsNotNull() {
            addCriterion("totality_review_num is not null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumEqualTo(Integer value) {
            addCriterion("totality_review_num =", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumNotEqualTo(Integer value) {
            addCriterion("totality_review_num <>", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumGreaterThan(Integer value) {
            addCriterion("totality_review_num >", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("totality_review_num >=", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumLessThan(Integer value) {
            addCriterion("totality_review_num <", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumLessThanOrEqualTo(Integer value) {
            addCriterion("totality_review_num <=", value, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumIn(List<Integer> values) {
            addCriterion("totality_review_num in", values, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumNotIn(List<Integer> values) {
            addCriterion("totality_review_num not in", values, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_num between", value1, value2, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewNumNotBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_num not between", value1, value2, "totalityReviewNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table deal
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}