package com.tech.pojo;

import java.io.Serializable;

public class DishImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.dish_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer dishImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.dish_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer dishId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dish_image.othe2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String othe2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dish_image
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.dish_image_id
     *
     * @return the value of dish_image.dish_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getDishImageId() {
        return dishImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.dish_image_id
     *
     * @param dishImageId the value for dish_image.dish_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDishImageId(Integer dishImageId) {
        this.dishImageId = dishImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.dish_id
     *
     * @return the value of dish_image.dish_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getDishId() {
        return dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.dish_id
     *
     * @param dishId the value for dish_image.dish_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDishId(Integer dishId) {
        this.dishId = dishId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.image_path
     *
     * @return the value of dish_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.image_path
     *
     * @param imagePath the value for dish_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.status
     *
     * @return the value of dish_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.status
     *
     * @param status the value for dish_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.other1
     *
     * @return the value of dish_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.other1
     *
     * @param other1 the value for dish_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dish_image.othe2
     *
     * @return the value of dish_image.othe2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOthe2() {
        return othe2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dish_image.othe2
     *
     * @param othe2 the value for dish_image.othe2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOthe2(String othe2) {
        this.othe2 = othe2 == null ? null : othe2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dish_image
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", dishImageId=").append(dishImageId);
        sb.append(", dishId=").append(dishId);
        sb.append(", imagePath=").append(imagePath);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", othe2=").append(othe2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}