package com.tech.pojo;

import java.io.Serializable;

public class Fans implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.focusfans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer focusfansId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.fans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer fansId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column fans.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table fans
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.focusfans_id
     *
     * @return the value of fans.focusfans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getFocusfansId() {
        return focusfansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.focusfans_id
     *
     * @param focusfansId the value for fans.focusfans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setFocusfansId(Integer focusfansId) {
        this.focusfansId = focusfansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.member_id
     *
     * @return the value of fans.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.member_id
     *
     * @param memberId the value for fans.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.fans_id
     *
     * @return the value of fans.fans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getFansId() {
        return fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.fans_id
     *
     * @param fansId the value for fans.fans_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setFansId(Integer fansId) {
        this.fansId = fansId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.status
     *
     * @return the value of fans.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.status
     *
     * @param status the value for fans.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.other1
     *
     * @return the value of fans.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.other1
     *
     * @param other1 the value for fans.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column fans.other2
     *
     * @return the value of fans.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column fans.other2
     *
     * @param other2 the value for fans.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table fans
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", focusfansId=").append(focusfansId);
        sb.append(", memberId=").append(memberId);
        sb.append(", fansId=").append(fansId);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}