package com.tech.pojo;

import java.io.Serializable;

public class Member implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_name
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String memberName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.member_telno
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Long memberTelno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.password
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.postbox
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String postbox;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer score;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_id
     *
     * @return the value of member.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_id
     *
     * @param memberId the value for member.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_name
     *
     * @return the value of member.member_name
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getMemberName() {
        return memberName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_name
     *
     * @param memberName the value for member.member_name
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setMemberName(String memberName) {
        this.memberName = memberName == null ? null : memberName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.member_telno
     *
     * @return the value of member.member_telno
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Long getMemberTelno() {
        return memberTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.member_telno
     *
     * @param memberTelno the value for member.member_telno
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setMemberTelno(Long memberTelno) {
        this.memberTelno = memberTelno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.password
     *
     * @return the value of member.password
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.password
     *
     * @param password the value for member.password
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.postbox
     *
     * @return the value of member.postbox
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getPostbox() {
        return postbox;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.postbox
     *
     * @param postbox the value for member.postbox
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setPostbox(String postbox) {
        this.postbox = postbox == null ? null : postbox.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.score
     *
     * @return the value of member.score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.score
     *
     * @param score the value for member.score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.status
     *
     * @return the value of member.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.status
     *
     * @param status the value for member.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.other1
     *
     * @return the value of member.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.other1
     *
     * @param other1 the value for member.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member.other2
     *
     * @return the value of member.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member.other2
     *
     * @param other2 the value for member.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", memberId=").append(memberId);
        sb.append(", memberName=").append(memberName);
        sb.append(", memberTelno=").append(memberTelno);
        sb.append(", password=").append(password);
        sb.append(", postbox=").append(postbox);
        sb.append(", score=").append(score);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}
