package com.tech.pojo;

import java.io.Serializable;
import java.util.Date;

public class MemberLike implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.like_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private Integer likeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.like_member_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private Integer likeMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.like_shop_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private Integer likeShopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.create_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.status
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column member_like.update_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table member_like
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.like_id
     *
     * @return the value of member_like.like_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public Integer getLikeId() {
        return likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.like_id
     *
     * @param likeId the value for member_like.like_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setLikeId(Integer likeId) {
        this.likeId = likeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.like_member_id
     *
     * @return the value of member_like.like_member_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public Integer getLikeMemberId() {
        return likeMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.like_member_id
     *
     * @param likeMemberId the value for member_like.like_member_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setLikeMemberId(Integer likeMemberId) {
        this.likeMemberId = likeMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.like_shop_id
     *
     * @return the value of member_like.like_shop_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public Integer getLikeShopId() {
        return likeShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.like_shop_id
     *
     * @param likeShopId the value for member_like.like_shop_id
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setLikeShopId(Integer likeShopId) {
        this.likeShopId = likeShopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.create_time
     *
     * @return the value of member_like.create_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.create_time
     *
     * @param createTime the value for member_like.create_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.status
     *
     * @return the value of member_like.status
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.status
     *
     * @param status the value for member_like.status
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column member_like.update_time
     *
     * @return the value of member_like.update_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column member_like.update_time
     *
     * @param updateTime the value for member_like.update_time
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table member_like
     *
     * @mbggenerated Thu Sep 12 13:02:23 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", likeId=").append(likeId);
        sb.append(", likeMemberId=").append(likeMemberId);
        sb.append(", likeShopId=").append(likeShopId);
        sb.append(", createTime=").append(createTime);
        sb.append(", status=").append(status);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}