package com.tech.pojo;

import java.util.ArrayList;
import java.util.List;

public class ReviewExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public ReviewExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andReviewIdIsNull() {
            addCriterion("review_id is null");
            return (Criteria) this;
        }

        public Criteria andReviewIdIsNotNull() {
            addCriterion("review_id is not null");
            return (Criteria) this;
        }

        public Criteria andReviewIdEqualTo(Integer value) {
            addCriterion("review_id =", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdNotEqualTo(Integer value) {
            addCriterion("review_id <>", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdGreaterThan(Integer value) {
            addCriterion("review_id >", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_id >=", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdLessThan(Integer value) {
            addCriterion("review_id <", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdLessThanOrEqualTo(Integer value) {
            addCriterion("review_id <=", value, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdIn(List<Integer> values) {
            addCriterion("review_id in", values, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdNotIn(List<Integer> values) {
            addCriterion("review_id not in", values, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdBetween(Integer value1, Integer value2) {
            addCriterion("review_id between", value1, value2, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewIdNotBetween(Integer value1, Integer value2) {
            addCriterion("review_id not between", value1, value2, "reviewId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdIsNull() {
            addCriterion("review_member_id is null");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdIsNotNull() {
            addCriterion("review_member_id is not null");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdEqualTo(Integer value) {
            addCriterion("review_member_id =", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdNotEqualTo(Integer value) {
            addCriterion("review_member_id <>", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdGreaterThan(Integer value) {
            addCriterion("review_member_id >", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("review_member_id >=", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdLessThan(Integer value) {
            addCriterion("review_member_id <", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdLessThanOrEqualTo(Integer value) {
            addCriterion("review_member_id <=", value, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdIn(List<Integer> values) {
            addCriterion("review_member_id in", values, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdNotIn(List<Integer> values) {
            addCriterion("review_member_id not in", values, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdBetween(Integer value1, Integer value2) {
            addCriterion("review_member_id between", value1, value2, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andReviewMemberIdNotBetween(Integer value1, Integer value2) {
            addCriterion("review_member_id not between", value1, value2, "reviewMemberId");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIsNull() {
            addCriterion("totality_review_score is null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIsNotNull() {
            addCriterion("totality_review_score is not null");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreEqualTo(Integer value) {
            addCriterion("totality_review_score =", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotEqualTo(Integer value) {
            addCriterion("totality_review_score <>", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreGreaterThan(Integer value) {
            addCriterion("totality_review_score >", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("totality_review_score >=", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreLessThan(Integer value) {
            addCriterion("totality_review_score <", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreLessThanOrEqualTo(Integer value) {
            addCriterion("totality_review_score <=", value, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreIn(List<Integer> values) {
            addCriterion("totality_review_score in", values, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotIn(List<Integer> values) {
            addCriterion("totality_review_score not in", values, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_score between", value1, value2, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andTotalityReviewScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("totality_review_score not between", value1, value2, "totalityReviewScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreIsNull() {
            addCriterion("surroundings_score is null");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreIsNotNull() {
            addCriterion("surroundings_score is not null");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreEqualTo(Integer value) {
            addCriterion("surroundings_score =", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreNotEqualTo(Integer value) {
            addCriterion("surroundings_score <>", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreGreaterThan(Integer value) {
            addCriterion("surroundings_score >", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("surroundings_score >=", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreLessThan(Integer value) {
            addCriterion("surroundings_score <", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreLessThanOrEqualTo(Integer value) {
            addCriterion("surroundings_score <=", value, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreIn(List<Integer> values) {
            addCriterion("surroundings_score in", values, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreNotIn(List<Integer> values) {
            addCriterion("surroundings_score not in", values, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreBetween(Integer value1, Integer value2) {
            addCriterion("surroundings_score between", value1, value2, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingsScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("surroundings_score not between", value1, value2, "surroundingsScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIsNull() {
            addCriterion("flavor_score is null");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIsNotNull() {
            addCriterion("flavor_score is not null");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreEqualTo(Integer value) {
            addCriterion("flavor_score =", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotEqualTo(Integer value) {
            addCriterion("flavor_score <>", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreGreaterThan(Integer value) {
            addCriterion("flavor_score >", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("flavor_score >=", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreLessThan(Integer value) {
            addCriterion("flavor_score <", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreLessThanOrEqualTo(Integer value) {
            addCriterion("flavor_score <=", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIn(List<Integer> values) {
            addCriterion("flavor_score in", values, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotIn(List<Integer> values) {
            addCriterion("flavor_score not in", values, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreBetween(Integer value1, Integer value2) {
            addCriterion("flavor_score between", value1, value2, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("flavor_score not between", value1, value2, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNull() {
            addCriterion("service_score is null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNotNull() {
            addCriterion("service_score is not null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreEqualTo(Integer value) {
            addCriterion("service_score =", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotEqualTo(Integer value) {
            addCriterion("service_score <>", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThan(Integer value) {
            addCriterion("service_score >", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("service_score >=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThan(Integer value) {
            addCriterion("service_score <", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThanOrEqualTo(Integer value) {
            addCriterion("service_score <=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIn(List<Integer> values) {
            addCriterion("service_score in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotIn(List<Integer> values) {
            addCriterion("service_score not in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreBetween(Integer value1, Integer value2) {
            addCriterion("service_score between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("service_score not between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreIsNull() {
            addCriterion("\"ingredients _score\" is null");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreIsNotNull() {
            addCriterion("\"ingredients _score\" is not null");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreEqualTo(Integer value) {
            addCriterion("\"ingredients _score\" =", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreNotEqualTo(Integer value) {
            addCriterion("\"ingredients _score\" <>", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreGreaterThan(Integer value) {
            addCriterion("\"ingredients _score\" >", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("\"ingredients _score\" >=", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreLessThan(Integer value) {
            addCriterion("\"ingredients _score\" <", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreLessThanOrEqualTo(Integer value) {
            addCriterion("\"ingredients _score\" <=", value, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreIn(List<Integer> values) {
            addCriterion("\"ingredients _score\" in", values, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreNotIn(List<Integer> values) {
            addCriterion("\"ingredients _score\" not in", values, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreBetween(Integer value1, Integer value2) {
            addCriterion("\"ingredients _score\" between", value1, value2, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andIngredientsScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("\"ingredients _score\" not between", value1, value2, "ingredientsScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreIsNull() {
            addCriterion("costperformance_score is null");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreIsNotNull() {
            addCriterion("costperformance_score is not null");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreEqualTo(Integer value) {
            addCriterion("costperformance_score =", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreNotEqualTo(Integer value) {
            addCriterion("costperformance_score <>", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreGreaterThan(Integer value) {
            addCriterion("costperformance_score >", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreGreaterThanOrEqualTo(Integer value) {
            addCriterion("costperformance_score >=", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreLessThan(Integer value) {
            addCriterion("costperformance_score <", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreLessThanOrEqualTo(Integer value) {
            addCriterion("costperformance_score <=", value, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreIn(List<Integer> values) {
            addCriterion("costperformance_score in", values, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreNotIn(List<Integer> values) {
            addCriterion("costperformance_score not in", values, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreBetween(Integer value1, Integer value2) {
            addCriterion("costperformance_score between", value1, value2, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andCostperformanceScoreNotBetween(Integer value1, Integer value2) {
            addCriterion("costperformance_score not between", value1, value2, "costperformanceScore");
            return (Criteria) this;
        }

        public Criteria andReviewCommentIsNull() {
            addCriterion("review_comment is null");
            return (Criteria) this;
        }

        public Criteria andReviewCommentIsNotNull() {
            addCriterion("review_comment is not null");
            return (Criteria) this;
        }

        public Criteria andReviewCommentEqualTo(String value) {
            addCriterion("review_comment =", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentNotEqualTo(String value) {
            addCriterion("review_comment <>", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentGreaterThan(String value) {
            addCriterion("review_comment >", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentGreaterThanOrEqualTo(String value) {
            addCriterion("review_comment >=", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentLessThan(String value) {
            addCriterion("review_comment <", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentLessThanOrEqualTo(String value) {
            addCriterion("review_comment <=", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentLike(String value) {
            addCriterion("review_comment like", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentNotLike(String value) {
            addCriterion("review_comment not like", value, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentIn(List<String> values) {
            addCriterion("review_comment in", values, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentNotIn(List<String> values) {
            addCriterion("review_comment not in", values, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentBetween(String value1, String value2) {
            addCriterion("review_comment between", value1, value2, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andReviewCommentNotBetween(String value1, String value2) {
            addCriterion("review_comment not between", value1, value2, "reviewComment");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIsNull() {
            addCriterion("person_consume is null");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIsNotNull() {
            addCriterion("person_consume is not null");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeEqualTo(Integer value) {
            addCriterion("person_consume =", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotEqualTo(Integer value) {
            addCriterion("person_consume <>", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeGreaterThan(Integer value) {
            addCriterion("person_consume >", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_consume >=", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeLessThan(Integer value) {
            addCriterion("person_consume <", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeLessThanOrEqualTo(Integer value) {
            addCriterion("person_consume <=", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIn(List<Integer> values) {
            addCriterion("person_consume in", values, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotIn(List<Integer> values) {
            addCriterion("person_consume not in", values, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeBetween(Integer value1, Integer value2) {
            addCriterion("person_consume between", value1, value2, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotBetween(Integer value1, Integer value2) {
            addCriterion("person_consume not between", value1, value2, "personConsume");
            return (Criteria) this;
        }

        public Criteria andLikeDishIsNull() {
            addCriterion("like_dish is null");
            return (Criteria) this;
        }

        public Criteria andLikeDishIsNotNull() {
            addCriterion("like_dish is not null");
            return (Criteria) this;
        }

        public Criteria andLikeDishEqualTo(String value) {
            addCriterion("like_dish =", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishNotEqualTo(String value) {
            addCriterion("like_dish <>", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishGreaterThan(String value) {
            addCriterion("like_dish >", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishGreaterThanOrEqualTo(String value) {
            addCriterion("like_dish >=", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishLessThan(String value) {
            addCriterion("like_dish <", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishLessThanOrEqualTo(String value) {
            addCriterion("like_dish <=", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishLike(String value) {
            addCriterion("like_dish like", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishNotLike(String value) {
            addCriterion("like_dish not like", value, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishIn(List<String> values) {
            addCriterion("like_dish in", values, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishNotIn(List<String> values) {
            addCriterion("like_dish not in", values, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishBetween(String value1, String value2) {
            addCriterion("like_dish between", value1, value2, "likeDish");
            return (Criteria) this;
        }

        public Criteria andLikeDishNotBetween(String value1, String value2) {
            addCriterion("like_dish not between", value1, value2, "likeDish");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumIsNull() {
            addCriterion("thumbs_up_num is null");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumIsNotNull() {
            addCriterion("thumbs_up_num is not null");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumEqualTo(Integer value) {
            addCriterion("thumbs_up_num =", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumNotEqualTo(Integer value) {
            addCriterion("thumbs_up_num <>", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumGreaterThan(Integer value) {
            addCriterion("thumbs_up_num >", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("thumbs_up_num >=", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumLessThan(Integer value) {
            addCriterion("thumbs_up_num <", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumLessThanOrEqualTo(Integer value) {
            addCriterion("thumbs_up_num <=", value, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumIn(List<Integer> values) {
            addCriterion("thumbs_up_num in", values, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumNotIn(List<Integer> values) {
            addCriterion("thumbs_up_num not in", values, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumBetween(Integer value1, Integer value2) {
            addCriterion("thumbs_up_num between", value1, value2, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andThumbsUpNumNotBetween(Integer value1, Integer value2) {
            addCriterion("thumbs_up_num not between", value1, value2, "thumbsUpNum");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}