package com.tech.pojo;

import java.io.Serializable;

public class Review implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer reviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer reviewMemberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.totality_review_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer totalityReviewScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.surroundings_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer surroundingsScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.flavor_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer flavorScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.service_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer serviceScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.ingredients _score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer ingredientsScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.costperformance_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer costperformanceScore;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.review_comment
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String reviewComment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.person_consume
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer personConsume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.like_dish
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String likeDish;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.thumbs_up_num
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer thumbsUpNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column review.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other2;

    public Review(){}
    public Review(Integer reviewMemberId, Integer shopId, Integer totalityReviewScore, Integer surroundingsScore, Integer flavorScore, Integer serviceScore, Integer ingredientsScore, Integer costperformanceScore, String reviewComment, Integer personConsume, String likeDish, Integer status, String other1) {
        this.reviewMemberId = reviewMemberId;
        this.shopId = shopId;
        this.totalityReviewScore = totalityReviewScore;
        this.surroundingsScore = surroundingsScore;
        this.flavorScore = flavorScore;
        this.serviceScore = serviceScore;
        this.ingredientsScore = ingredientsScore;
        this.costperformanceScore = costperformanceScore;
        this.reviewComment = reviewComment;
        this.personConsume = personConsume;
        this.likeDish = likeDish;
        this.status = status;
        this.other1 = other1;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_id
     *
     * @return the value of review.review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getReviewId() {
        return reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_id
     *
     * @param reviewId the value for review.review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setReviewId(Integer reviewId) {
        this.reviewId = reviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_member_id
     *
     * @return the value of review.review_member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getReviewMemberId() {
        return reviewMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_member_id
     *
     * @param reviewMemberId the value for review.review_member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setReviewMemberId(Integer reviewMemberId) {
        this.reviewMemberId = reviewMemberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.shop_id
     *
     * @return the value of review.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.shop_id
     *
     * @param shopId the value for review.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.totality_review_score
     *
     * @return the value of review.totality_review_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getTotalityReviewScore() {
        return totalityReviewScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.totality_review_score
     *
     * @param totalityReviewScore the value for review.totality_review_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setTotalityReviewScore(Integer totalityReviewScore) {
        this.totalityReviewScore = totalityReviewScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.surroundings_score
     *
     * @return the value of review.surroundings_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getSurroundingsScore() {
        return surroundingsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.surroundings_score
     *
     * @param surroundingsScore the value for review.surroundings_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setSurroundingsScore(Integer surroundingsScore) {
        this.surroundingsScore = surroundingsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.flavor_score
     *
     * @return the value of review.flavor_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getFlavorScore() {
        return flavorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.flavor_score
     *
     * @param flavorScore the value for review.flavor_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setFlavorScore(Integer flavorScore) {
        this.flavorScore = flavorScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.service_score
     *
     * @return the value of review.service_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getServiceScore() {
        return serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.service_score
     *
     * @param serviceScore the value for review.service_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setServiceScore(Integer serviceScore) {
        this.serviceScore = serviceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.ingredients _score
     *
     * @return the value of review.ingredients _score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getIngredientsScore() {
        return ingredientsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.ingredients _score
     *
     * @param ingredientsScore the value for review.ingredients _score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setIngredientsScore(Integer ingredientsScore) {
        this.ingredientsScore = ingredientsScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.costperformance_score
     *
     * @return the value of review.costperformance_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getCostperformanceScore() {
        return costperformanceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.costperformance_score
     *
     * @param costperformanceScore the value for review.costperformance_score
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setCostperformanceScore(Integer costperformanceScore) {
        this.costperformanceScore = costperformanceScore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.review_comment
     *
     * @return the value of review.review_comment
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getReviewComment() {
        return reviewComment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.review_comment
     *
     * @param reviewComment the value for review.review_comment
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setReviewComment(String reviewComment) {
        this.reviewComment = reviewComment == null ? null : reviewComment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.person_consume
     *
     * @return the value of review.person_consume
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getPersonConsume() {
        return personConsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.person_consume
     *
     * @param personConsume the value for review.person_consume
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setPersonConsume(Integer personConsume) {
        this.personConsume = personConsume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.like_dish
     *
     * @return the value of review.like_dish
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getLikeDish() {
        return likeDish;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.like_dish
     *
     * @param likeDish the value for review.like_dish
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setLikeDish(String likeDish) {
        this.likeDish = likeDish == null ? null : likeDish.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.thumbs_up_num
     *
     * @return the value of review.thumbs_up_num
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getThumbsUpNum() {
        return thumbsUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.thumbs_up_num
     *
     * @param thumbsUpNum the value for review.thumbs_up_num
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setThumbsUpNum(Integer thumbsUpNum) {
        this.thumbsUpNum = thumbsUpNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.status
     *
     * @return the value of review.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.status
     *
     * @param status the value for review.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.other1
     *
     * @return the value of review.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.other1
     *
     * @param other1 the value for review.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column review.other2
     *
     * @return the value of review.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column review.other2
     *
     * @param other2 the value for review.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table review
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reviewId=").append(reviewId);
        sb.append(", reviewMemberId=").append(reviewMemberId);
        sb.append(", shopId=").append(shopId);
        sb.append(", totalityReviewScore=").append(totalityReviewScore);
        sb.append(", surroundingsScore=").append(surroundingsScore);
        sb.append(", flavorScore=").append(flavorScore);
        sb.append(", serviceScore=").append(serviceScore);
        sb.append(", ingredientsScore=").append(ingredientsScore);
        sb.append(", costperformanceScore=").append(costperformanceScore);
        sb.append(", reviewComment=").append(reviewComment);
        sb.append(", personConsume=").append(personConsume);
        sb.append(", likeDish=").append(likeDish);
        sb.append(", thumbsUpNum=").append(thumbsUpNum);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}