package com.tech.pojo;

import java.io.Serializable;

public class ReviewsImage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.reviews_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer reviewsImageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.dish_review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer dishReviewId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String imagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reviews_image.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table reviews_image
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.reviews_image_id
     *
     * @return the value of reviews_image.reviews_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getReviewsImageId() {
        return reviewsImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.reviews_image_id
     *
     * @param reviewsImageId the value for reviews_image.reviews_image_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setReviewsImageId(Integer reviewsImageId) {
        this.reviewsImageId = reviewsImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.dish_review_id
     *
     * @return the value of reviews_image.dish_review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getDishReviewId() {
        return dishReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.dish_review_id
     *
     * @param dishReviewId the value for reviews_image.dish_review_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDishReviewId(Integer dishReviewId) {
        this.dishReviewId = dishReviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.image_path
     *
     * @return the value of reviews_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getImagePath() {
        return imagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.image_path
     *
     * @param imagePath the value for reviews_image.image_path
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath == null ? null : imagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.status
     *
     * @return the value of reviews_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.status
     *
     * @param status the value for reviews_image.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.other1
     *
     * @return the value of reviews_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.other1
     *
     * @param other1 the value for reviews_image.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reviews_image.other2
     *
     * @return the value of reviews_image.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reviews_image.other2
     *
     * @param other2 the value for reviews_image.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table reviews_image
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reviewsImageId=").append(reviewsImageId);
        sb.append(", dishReviewId=").append(dishReviewId);
        sb.append(", imagePath=").append(imagePath);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}