package com.tech.pojo;

import java.util.ArrayList;
import java.util.List;

public class ShopExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public ShopExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andShopIdIsNull() {
            addCriterion("shop_id is null");
            return (Criteria) this;
        }

        public Criteria andShopIdIsNotNull() {
            addCriterion("shop_id is not null");
            return (Criteria) this;
        }

        public Criteria andShopIdEqualTo(Integer value) {
            addCriterion("shop_id =", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotEqualTo(Integer value) {
            addCriterion("shop_id <>", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThan(Integer value) {
            addCriterion("shop_id >", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("shop_id >=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThan(Integer value) {
            addCriterion("shop_id <", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdLessThanOrEqualTo(Integer value) {
            addCriterion("shop_id <=", value, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdIn(List<Integer> values) {
            addCriterion("shop_id in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotIn(List<Integer> values) {
            addCriterion("shop_id not in", values, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdBetween(Integer value1, Integer value2) {
            addCriterion("shop_id between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopIdNotBetween(Integer value1, Integer value2) {
            addCriterion("shop_id not between", value1, value2, "shopId");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameIsNull() {
            addCriterion("branchshop_name is null");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameIsNotNull() {
            addCriterion("branchshop_name is not null");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameEqualTo(String value) {
            addCriterion("branchshop_name =", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameNotEqualTo(String value) {
            addCriterion("branchshop_name <>", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameGreaterThan(String value) {
            addCriterion("branchshop_name >", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameGreaterThanOrEqualTo(String value) {
            addCriterion("branchshop_name >=", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameLessThan(String value) {
            addCriterion("branchshop_name <", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameLessThanOrEqualTo(String value) {
            addCriterion("branchshop_name <=", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameLike(String value) {
            addCriterion("branchshop_name like", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameNotLike(String value) {
            addCriterion("branchshop_name not like", value, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameIn(List<String> values) {
            addCriterion("branchshop_name in", values, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameNotIn(List<String> values) {
            addCriterion("branchshop_name not in", values, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameBetween(String value1, String value2) {
            addCriterion("branchshop_name between", value1, value2, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andBranchshopNameNotBetween(String value1, String value2) {
            addCriterion("branchshop_name not between", value1, value2, "branchshopName");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNull() {
            addCriterion("keyword is null");
            return (Criteria) this;
        }

        public Criteria andKeywordIsNotNull() {
            addCriterion("keyword is not null");
            return (Criteria) this;
        }

        public Criteria andKeywordEqualTo(String value) {
            addCriterion("keyword =", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotEqualTo(String value) {
            addCriterion("keyword <>", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThan(String value) {
            addCriterion("keyword >", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordGreaterThanOrEqualTo(String value) {
            addCriterion("keyword >=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThan(String value) {
            addCriterion("keyword <", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLessThanOrEqualTo(String value) {
            addCriterion("keyword <=", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordLike(String value) {
            addCriterion("keyword like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotLike(String value) {
            addCriterion("keyword not like", value, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordIn(List<String> values) {
            addCriterion("keyword in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotIn(List<String> values) {
            addCriterion("keyword not in", values, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordBetween(String value1, String value2) {
            addCriterion("keyword between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andKeywordNotBetween(String value1, String value2) {
            addCriterion("keyword not between", value1, value2, "keyword");
            return (Criteria) this;
        }

        public Criteria andMainImageIsNull() {
            addCriterion("main_image is null");
            return (Criteria) this;
        }

        public Criteria andMainImageIsNotNull() {
            addCriterion("main_image is not null");
            return (Criteria) this;
        }

        public Criteria andMainImageEqualTo(String value) {
            addCriterion("main_image =", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageNotEqualTo(String value) {
            addCriterion("main_image <>", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageGreaterThan(String value) {
            addCriterion("main_image >", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageGreaterThanOrEqualTo(String value) {
            addCriterion("main_image >=", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageLessThan(String value) {
            addCriterion("main_image <", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageLessThanOrEqualTo(String value) {
            addCriterion("main_image <=", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageLike(String value) {
            addCriterion("main_image like", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageNotLike(String value) {
            addCriterion("main_image not like", value, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageIn(List<String> values) {
            addCriterion("main_image in", values, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageNotIn(List<String> values) {
            addCriterion("main_image not in", values, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageBetween(String value1, String value2) {
            addCriterion("main_image between", value1, value2, "mainImage");
            return (Criteria) this;
        }

        public Criteria andMainImageNotBetween(String value1, String value2) {
            addCriterion("main_image not between", value1, value2, "mainImage");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceIsNull() {
            addCriterion("shop_add_province is null");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceIsNotNull() {
            addCriterion("shop_add_province is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceEqualTo(String value) {
            addCriterion("shop_add_province =", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceNotEqualTo(String value) {
            addCriterion("shop_add_province <>", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceGreaterThan(String value) {
            addCriterion("shop_add_province >", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceGreaterThanOrEqualTo(String value) {
            addCriterion("shop_add_province >=", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceLessThan(String value) {
            addCriterion("shop_add_province <", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceLessThanOrEqualTo(String value) {
            addCriterion("shop_add_province <=", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceLike(String value) {
            addCriterion("shop_add_province like", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceNotLike(String value) {
            addCriterion("shop_add_province not like", value, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceIn(List<String> values) {
            addCriterion("shop_add_province in", values, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceNotIn(List<String> values) {
            addCriterion("shop_add_province not in", values, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceBetween(String value1, String value2) {
            addCriterion("shop_add_province between", value1, value2, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddProvinceNotBetween(String value1, String value2) {
            addCriterion("shop_add_province not between", value1, value2, "shopAddProvince");
            return (Criteria) this;
        }

        public Criteria andShopAddCityIsNull() {
            addCriterion("shop_add_city is null");
            return (Criteria) this;
        }

        public Criteria andShopAddCityIsNotNull() {
            addCriterion("shop_add_city is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddCityEqualTo(String value) {
            addCriterion("shop_add_city =", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityNotEqualTo(String value) {
            addCriterion("shop_add_city <>", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityGreaterThan(String value) {
            addCriterion("shop_add_city >", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityGreaterThanOrEqualTo(String value) {
            addCriterion("shop_add_city >=", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityLessThan(String value) {
            addCriterion("shop_add_city <", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityLessThanOrEqualTo(String value) {
            addCriterion("shop_add_city <=", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityLike(String value) {
            addCriterion("shop_add_city like", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityNotLike(String value) {
            addCriterion("shop_add_city not like", value, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityIn(List<String> values) {
            addCriterion("shop_add_city in", values, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityNotIn(List<String> values) {
            addCriterion("shop_add_city not in", values, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityBetween(String value1, String value2) {
            addCriterion("shop_add_city between", value1, value2, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddCityNotBetween(String value1, String value2) {
            addCriterion("shop_add_city not between", value1, value2, "shopAddCity");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetIsNull() {
            addCriterion("shop_add_street is null");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetIsNotNull() {
            addCriterion("shop_add_street is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetEqualTo(String value) {
            addCriterion("shop_add_street =", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetNotEqualTo(String value) {
            addCriterion("shop_add_street <>", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetGreaterThan(String value) {
            addCriterion("shop_add_street >", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetGreaterThanOrEqualTo(String value) {
            addCriterion("shop_add_street >=", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetLessThan(String value) {
            addCriterion("shop_add_street <", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetLessThanOrEqualTo(String value) {
            addCriterion("shop_add_street <=", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetLike(String value) {
            addCriterion("shop_add_street like", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetNotLike(String value) {
            addCriterion("shop_add_street not like", value, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetIn(List<String> values) {
            addCriterion("shop_add_street in", values, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetNotIn(List<String> values) {
            addCriterion("shop_add_street not in", values, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetBetween(String value1, String value2) {
            addCriterion("shop_add_street between", value1, value2, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddStreetNotBetween(String value1, String value2) {
            addCriterion("shop_add_street not between", value1, value2, "shopAddStreet");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaIsNull() {
            addCriterion("shop_add_area is null");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaIsNotNull() {
            addCriterion("shop_add_area is not null");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaEqualTo(String value) {
            addCriterion("shop_add_area =", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaNotEqualTo(String value) {
            addCriterion("shop_add_area <>", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaGreaterThan(String value) {
            addCriterion("shop_add_area >", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaGreaterThanOrEqualTo(String value) {
            addCriterion("shop_add_area >=", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaLessThan(String value) {
            addCriterion("shop_add_area <", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaLessThanOrEqualTo(String value) {
            addCriterion("shop_add_area <=", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaLike(String value) {
            addCriterion("shop_add_area like", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaNotLike(String value) {
            addCriterion("shop_add_area not like", value, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaIn(List<String> values) {
            addCriterion("shop_add_area in", values, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaNotIn(List<String> values) {
            addCriterion("shop_add_area not in", values, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaBetween(String value1, String value2) {
            addCriterion("shop_add_area between", value1, value2, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andShopAddAreaNotBetween(String value1, String value2) {
            addCriterion("shop_add_area not between", value1, value2, "shopAddArea");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailIsNull() {
            addCriterion("stop_add_detail is null");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailIsNotNull() {
            addCriterion("stop_add_detail is not null");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailEqualTo(String value) {
            addCriterion("stop_add_detail =", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailNotEqualTo(String value) {
            addCriterion("stop_add_detail <>", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailGreaterThan(String value) {
            addCriterion("stop_add_detail >", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailGreaterThanOrEqualTo(String value) {
            addCriterion("stop_add_detail >=", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailLessThan(String value) {
            addCriterion("stop_add_detail <", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailLessThanOrEqualTo(String value) {
            addCriterion("stop_add_detail <=", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailLike(String value) {
            addCriterion("stop_add_detail like", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailNotLike(String value) {
            addCriterion("stop_add_detail not like", value, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailIn(List<String> values) {
            addCriterion("stop_add_detail in", values, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailNotIn(List<String> values) {
            addCriterion("stop_add_detail not in", values, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailBetween(String value1, String value2) {
            addCriterion("stop_add_detail between", value1, value2, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andStopAddDetailNotBetween(String value1, String value2) {
            addCriterion("stop_add_detail not between", value1, value2, "stopAddDetail");
            return (Criteria) this;
        }

        public Criteria andTelno1IsNull() {
            addCriterion("telno1 is null");
            return (Criteria) this;
        }

        public Criteria andTelno1IsNotNull() {
            addCriterion("telno1 is not null");
            return (Criteria) this;
        }

        public Criteria andTelno1EqualTo(Integer value) {
            addCriterion("telno1 =", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1NotEqualTo(Integer value) {
            addCriterion("telno1 <>", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1GreaterThan(Integer value) {
            addCriterion("telno1 >", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1GreaterThanOrEqualTo(Integer value) {
            addCriterion("telno1 >=", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1LessThan(Integer value) {
            addCriterion("telno1 <", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1LessThanOrEqualTo(Integer value) {
            addCriterion("telno1 <=", value, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1In(List<Integer> values) {
            addCriterion("telno1 in", values, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1NotIn(List<Integer> values) {
            addCriterion("telno1 not in", values, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1Between(Integer value1, Integer value2) {
            addCriterion("telno1 between", value1, value2, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno1NotBetween(Integer value1, Integer value2) {
            addCriterion("telno1 not between", value1, value2, "telno1");
            return (Criteria) this;
        }

        public Criteria andTelno2IsNull() {
            addCriterion("telno2 is null");
            return (Criteria) this;
        }

        public Criteria andTelno2IsNotNull() {
            addCriterion("telno2 is not null");
            return (Criteria) this;
        }

        public Criteria andTelno2EqualTo(Integer value) {
            addCriterion("telno2 =", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2NotEqualTo(Integer value) {
            addCriterion("telno2 <>", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2GreaterThan(Integer value) {
            addCriterion("telno2 >", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2GreaterThanOrEqualTo(Integer value) {
            addCriterion("telno2 >=", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2LessThan(Integer value) {
            addCriterion("telno2 <", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2LessThanOrEqualTo(Integer value) {
            addCriterion("telno2 <=", value, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2In(List<Integer> values) {
            addCriterion("telno2 in", values, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2NotIn(List<Integer> values) {
            addCriterion("telno2 not in", values, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2Between(Integer value1, Integer value2) {
            addCriterion("telno2 between", value1, value2, "telno2");
            return (Criteria) this;
        }

        public Criteria andTelno2NotBetween(Integer value1, Integer value2) {
            addCriterion("telno2 not between", value1, value2, "telno2");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeIsNull() {
            addCriterion("business_time is null");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeIsNotNull() {
            addCriterion("business_time is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeEqualTo(String value) {
            addCriterion("business_time =", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeNotEqualTo(String value) {
            addCriterion("business_time <>", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeGreaterThan(String value) {
            addCriterion("business_time >", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeGreaterThanOrEqualTo(String value) {
            addCriterion("business_time >=", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeLessThan(String value) {
            addCriterion("business_time <", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeLessThanOrEqualTo(String value) {
            addCriterion("business_time <=", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeLike(String value) {
            addCriterion("business_time like", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeNotLike(String value) {
            addCriterion("business_time not like", value, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeIn(List<String> values) {
            addCriterion("business_time in", values, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeNotIn(List<String> values) {
            addCriterion("business_time not in", values, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeBetween(String value1, String value2) {
            addCriterion("business_time between", value1, value2, "businessTime");
            return (Criteria) this;
        }

        public Criteria andBusinessTimeNotBetween(String value1, String value2) {
            addCriterion("business_time not between", value1, value2, "businessTime");
            return (Criteria) this;
        }

        public Criteria andStarClassIsNull() {
            addCriterion("star_class is null");
            return (Criteria) this;
        }

        public Criteria andStarClassIsNotNull() {
            addCriterion("star_class is not null");
            return (Criteria) this;
        }

        public Criteria andStarClassEqualTo(Integer value) {
            addCriterion("star_class =", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassNotEqualTo(Integer value) {
            addCriterion("star_class <>", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassGreaterThan(Integer value) {
            addCriterion("star_class >", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassGreaterThanOrEqualTo(Integer value) {
            addCriterion("star_class >=", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassLessThan(Integer value) {
            addCriterion("star_class <", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassLessThanOrEqualTo(Integer value) {
            addCriterion("star_class <=", value, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassIn(List<Integer> values) {
            addCriterion("star_class in", values, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassNotIn(List<Integer> values) {
            addCriterion("star_class not in", values, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassBetween(Integer value1, Integer value2) {
            addCriterion("star_class between", value1, value2, "starClass");
            return (Criteria) this;
        }

        public Criteria andStarClassNotBetween(Integer value1, Integer value2) {
            addCriterion("star_class not between", value1, value2, "starClass");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIsNull() {
            addCriterion("person_consume is null");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIsNotNull() {
            addCriterion("person_consume is not null");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeEqualTo(Integer value) {
            addCriterion("person_consume =", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotEqualTo(Integer value) {
            addCriterion("person_consume <>", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeGreaterThan(Integer value) {
            addCriterion("person_consume >", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeGreaterThanOrEqualTo(Integer value) {
            addCriterion("person_consume >=", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeLessThan(Integer value) {
            addCriterion("person_consume <", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeLessThanOrEqualTo(Integer value) {
            addCriterion("person_consume <=", value, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeIn(List<Integer> values) {
            addCriterion("person_consume in", values, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotIn(List<Integer> values) {
            addCriterion("person_consume not in", values, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeBetween(Integer value1, Integer value2) {
            addCriterion("person_consume between", value1, value2, "personConsume");
            return (Criteria) this;
        }

        public Criteria andPersonConsumeNotBetween(Integer value1, Integer value2) {
            addCriterion("person_consume not between", value1, value2, "personConsume");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIsNull() {
            addCriterion("flavor_score is null");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIsNotNull() {
            addCriterion("flavor_score is not null");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreEqualTo(Float value) {
            addCriterion("flavor_score =", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotEqualTo(Float value) {
            addCriterion("flavor_score <>", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreGreaterThan(Float value) {
            addCriterion("flavor_score >", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreGreaterThanOrEqualTo(Float value) {
            addCriterion("flavor_score >=", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreLessThan(Float value) {
            addCriterion("flavor_score <", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreLessThanOrEqualTo(Float value) {
            addCriterion("flavor_score <=", value, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreIn(List<Float> values) {
            addCriterion("flavor_score in", values, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotIn(List<Float> values) {
            addCriterion("flavor_score not in", values, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreBetween(Float value1, Float value2) {
            addCriterion("flavor_score between", value1, value2, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andFlavorScoreNotBetween(Float value1, Float value2) {
            addCriterion("flavor_score not between", value1, value2, "flavorScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreIsNull() {
            addCriterion("surrounding_score is null");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreIsNotNull() {
            addCriterion("surrounding_score is not null");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreEqualTo(Float value) {
            addCriterion("surrounding_score =", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreNotEqualTo(Float value) {
            addCriterion("surrounding_score <>", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreGreaterThan(Float value) {
            addCriterion("surrounding_score >", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreGreaterThanOrEqualTo(Float value) {
            addCriterion("surrounding_score >=", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreLessThan(Float value) {
            addCriterion("surrounding_score <", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreLessThanOrEqualTo(Float value) {
            addCriterion("surrounding_score <=", value, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreIn(List<Float> values) {
            addCriterion("surrounding_score in", values, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreNotIn(List<Float> values) {
            addCriterion("surrounding_score not in", values, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreBetween(Float value1, Float value2) {
            addCriterion("surrounding_score between", value1, value2, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andSurroundingScoreNotBetween(Float value1, Float value2) {
            addCriterion("surrounding_score not between", value1, value2, "surroundingScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNull() {
            addCriterion("service_score is null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIsNotNull() {
            addCriterion("service_score is not null");
            return (Criteria) this;
        }

        public Criteria andServiceScoreEqualTo(Float value) {
            addCriterion("service_score =", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotEqualTo(Float value) {
            addCriterion("service_score <>", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThan(Float value) {
            addCriterion("service_score >", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreGreaterThanOrEqualTo(Float value) {
            addCriterion("service_score >=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThan(Float value) {
            addCriterion("service_score <", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreLessThanOrEqualTo(Float value) {
            addCriterion("service_score <=", value, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreIn(List<Float> values) {
            addCriterion("service_score in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotIn(List<Float> values) {
            addCriterion("service_score not in", values, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreBetween(Float value1, Float value2) {
            addCriterion("service_score between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andServiceScoreNotBetween(Float value1, Float value2) {
            addCriterion("service_score not between", value1, value2, "serviceScore");
            return (Criteria) this;
        }

        public Criteria andLongiLatiIsNull() {
            addCriterion("longi_lati is null");
            return (Criteria) this;
        }

        public Criteria andLongiLatiIsNotNull() {
            addCriterion("longi_lati is not null");
            return (Criteria) this;
        }

        public Criteria andLongiLatiEqualTo(String value) {
            addCriterion("longi_lati =", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiNotEqualTo(String value) {
            addCriterion("longi_lati <>", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiGreaterThan(String value) {
            addCriterion("longi_lati >", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiGreaterThanOrEqualTo(String value) {
            addCriterion("longi_lati >=", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiLessThan(String value) {
            addCriterion("longi_lati <", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiLessThanOrEqualTo(String value) {
            addCriterion("longi_lati <=", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiLike(String value) {
            addCriterion("longi_lati like", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiNotLike(String value) {
            addCriterion("longi_lati not like", value, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiIn(List<String> values) {
            addCriterion("longi_lati in", values, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiNotIn(List<String> values) {
            addCriterion("longi_lati not in", values, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiBetween(String value1, String value2) {
            addCriterion("longi_lati between", value1, value2, "longiLati");
            return (Criteria) this;
        }

        public Criteria andLongiLatiNotBetween(String value1, String value2) {
            addCriterion("longi_lati not between", value1, value2, "longiLati");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andOther1IsNull() {
            addCriterion("other1 is null");
            return (Criteria) this;
        }

        public Criteria andOther1IsNotNull() {
            addCriterion("other1 is not null");
            return (Criteria) this;
        }

        public Criteria andOther1EqualTo(String value) {
            addCriterion("other1 =", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotEqualTo(String value) {
            addCriterion("other1 <>", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThan(String value) {
            addCriterion("other1 >", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1GreaterThanOrEqualTo(String value) {
            addCriterion("other1 >=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThan(String value) {
            addCriterion("other1 <", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1LessThanOrEqualTo(String value) {
            addCriterion("other1 <=", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Like(String value) {
            addCriterion("other1 like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotLike(String value) {
            addCriterion("other1 not like", value, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1In(List<String> values) {
            addCriterion("other1 in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotIn(List<String> values) {
            addCriterion("other1 not in", values, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1Between(String value1, String value2) {
            addCriterion("other1 between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther1NotBetween(String value1, String value2) {
            addCriterion("other1 not between", value1, value2, "other1");
            return (Criteria) this;
        }

        public Criteria andOther2IsNull() {
            addCriterion("other2 is null");
            return (Criteria) this;
        }

        public Criteria andOther2IsNotNull() {
            addCriterion("other2 is not null");
            return (Criteria) this;
        }

        public Criteria andOther2EqualTo(String value) {
            addCriterion("other2 =", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotEqualTo(String value) {
            addCriterion("other2 <>", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThan(String value) {
            addCriterion("other2 >", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2GreaterThanOrEqualTo(String value) {
            addCriterion("other2 >=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThan(String value) {
            addCriterion("other2 <", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2LessThanOrEqualTo(String value) {
            addCriterion("other2 <=", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Like(String value) {
            addCriterion("other2 like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotLike(String value) {
            addCriterion("other2 not like", value, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2In(List<String> values) {
            addCriterion("other2 in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotIn(List<String> values) {
            addCriterion("other2 not in", values, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2Between(String value1, String value2) {
            addCriterion("other2 between", value1, value2, "other2");
            return (Criteria) this;
        }

        public Criteria andOther2NotBetween(String value1, String value2) {
            addCriterion("other2 not between", value1, value2, "other2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated do_not_delete_during_merge Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table shop
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}