package com.tech.pojo;

import java.io.Serializable;

public class Wishlist implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.wishlist_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer wishlistId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer memberId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer shopId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wishlist.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private String other2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table wishlist
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.wishlist_id
     *
     * @return the value of wishlist.wishlist_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getWishlistId() {
        return wishlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.wishlist_id
     *
     * @param wishlistId the value for wishlist.wishlist_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setWishlistId(Integer wishlistId) {
        this.wishlistId = wishlistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.member_id
     *
     * @return the value of wishlist.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.member_id
     *
     * @param memberId the value for wishlist.member_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setMemberId(Integer memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.shop_id
     *
     * @return the value of wishlist.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getShopId() {
        return shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.shop_id
     *
     * @param shopId the value for wishlist.shop_id
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setShopId(Integer shopId) {
        this.shopId = shopId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.status
     *
     * @return the value of wishlist.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.status
     *
     * @param status the value for wishlist.status
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.other1
     *
     * @return the value of wishlist.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther1() {
        return other1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.other1
     *
     * @param other1 the value for wishlist.other1
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther1(String other1) {
        this.other1 = other1 == null ? null : other1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wishlist.other2
     *
     * @return the value of wishlist.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public String getOther2() {
        return other2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wishlist.other2
     *
     * @param other2 the value for wishlist.other2
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    public void setOther2(String other2) {
        this.other2 = other2 == null ? null : other2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wishlist
     *
     * @mbggenerated Thu Sep 05 20:11:35 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", wishlistId=").append(wishlistId);
        sb.append(", memberId=").append(memberId);
        sb.append(", shopId=").append(shopId);
        sb.append(", status=").append(status);
        sb.append(", other1=").append(other1);
        sb.append(", other2=").append(other2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}